create table devices (
    id number(19,0) generated by default as identity primary key,
    name varchar2(100 char) not null,
    type varchar2(30 char) not null,
    created_at timestamp(6) with time zone not null,
    constraint uk_devices_name unique (name)
);

create table network_interfaces (
    id number(19,0) generated by default as identity primary key,
    device_id number(19,0) not null,
    name varchar2(50 char) not null,
    mac_address varchar2(17 char) not null,
    created_at timestamp(6) with time zone not null,
    constraint fk_interface_device foreign key (device_id) references devices(id),
    constraint uk_network_interface_device_name unique (device_id, name),
    constraint uk_network_interface_mac unique (mac_address)
);

create table subnets (
    id number(19,0) generated by default as identity primary key,
    network_address varchar2(15 char) not null,
    prefix_length number(10,0) not null,
    gateway_address varchar2(15 char),
    created_at timestamp(6) with time zone not null,
    constraint uk_subnet_network_prefix unique (network_address, prefix_length)
);

create table ip_addresses (
    id number(19,0) generated by default as identity primary key,
    subnet_id number(19,0) not null,
    address varchar2(15 char) not null,
    address_numeric number(19,0) not null,
    status varchar2(20 char) not null,
    network_interface_id number(19,0),
    allocated_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    constraint fk_ip_subnet foreign key (subnet_id) references subnets(id),
    constraint fk_ip_interface foreign key (network_interface_id) references network_interfaces(id),
    constraint uk_ip_address_subnet_address unique (subnet_id, address)
);

create index idx_ip_address_subnet_status_numeric
    on ip_addresses (subnet_id, status, address_numeric);
